services:
  - type: web
    name: insurance-estimator-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python prepare_data.py && python train.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
